### ISSUE TITLE
West crashes if manifest's self.path is missing

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#245]
```
Traceback (most recent call last):
  File "/home/mbolivar/.virtualenvs/west/bin/west", line 10, in <module>
    sys.exit(main())
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/site-packages/west/_bootstrap/main.py", line 481, in main
    init(wrap_argv[1:])
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/site-packages/west/_bootstrap/main.py", line 244, in init
    bootstrap(args)
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/site-packages/west/_bootstrap/main.py", line 322, in bootstrap
    wrap(cmd)
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/site-packages/west/_bootstrap/main.py", line 465, in wrap
    west.main.main(argv)
  File "/home/mbolivar/abs/.west/west/src/west/main.py", line 580, in main
    args.handler(args, unknown)
  File "/home/mbolivar/abs/.west/west/src/west/main.py", line 299, in command_handler
    command.run(known_args, unknown_args)
  File "/home/mbolivar/abs/.west/west/src/west/commands/command.py", line 90, in run
    self.do_run(args, unknown)
  File "/home/mbolivar/abs/.west/west/src/west/commands/project.py", line 63, in do_run
    projects = Manifest.from_file(manifest_file).projects
  File "/home/mbolivar/abs/.west/west/src/west/manifest.py", line 91, in from_file
    return Manifest(source_file=source_file, sections=sections)
  File "/home/mbolivar/abs/.west/west/src/west/manifest.py", line 182, in __init__
    self._load(self._data, sections)
  File "/home/mbolivar/abs/.west/west/src/west/manifest.py", line 259, in _load
    project = SpecialProject(path, path=path, west_commands=west_commands)
  File "/home/mbolivar/abs/.west/west/src/west/manifest.py", line 668, in __init__
    self.path))
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/mbolivar/.virtualenvs/west/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
```

**Comment by mbolivar** [comment]
This is no longer a problem on master
