### ISSUE TITLE
west crashes on `west update`

### ISSUE THREAD

**Issue by JohnVillalovos** [zephyrproject-rtos/west#561]
The `west.yml` file:
```
$ cat west.yml
manifest:
  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: acpica
      remote: github
      repo-path: acpica/acpica
      path: tools/acpica
      revision: refs/tags/R01_05_21
      clone-depth: 1
```

Version and initialize
```
$ west --version
West version: v0.12.0
$ west init -l
=== Initializing from existing manifest repository temp
--- Creating /home/jlvillal/testing/.west and local configuration file
=== Initialized. Now run "west update" inside /home/jlvillal/testing.
```

Where things go wrong:
```

$ west --verbose update
west.manifest: loading /home/jlvillal/testing/temp/west.yml
west.manifest: group-filter: unset
west.manifest: added project acpica path tools/acpica revision refs/tags/R01_05_21 from /home/jlvillal/testing/temp/west.yml
west.manifest: loaded /home/jlvillal/testing/temp/west.yml
=== updating acpica (tools/acpica):
--- acpica: initializing
west.manifest: running 'git init --initial-branch=init_placeholder /home/jlvillal/testing/tools/acpica' in /home/jlvillal/testing
Initialized empty Git repository in /home/jlvillal/testing/tools/acpica/.git/
west.manifest: "git init --initial-branch=init_placeholder /home/jlvillal/testing/tools/acpica" exit code: 0 stdout: None stderr: None
west.manifest: running 'git remote add -- github https://github.com/acpica/acpica' in /home/jlvillal/testing/tools/acpica
west.manifest: "git remote add -- github https://github.com/acpica/acpica" exit code: 0 stdout: None stderr: None
west.manifest: running 'git cat-file -t refs/tags/R01_05_21' in /home/jlvillal/testing/tools/acpica
west.manifest: "git cat-file -t refs/tags/R01_05_21" exit code: 128 stdout: b'' stderr: b'fatal: Not a valid object name refs/tags/R01_05_21\n'
--- acpica: fetching, need revision refs/tags/R01_05_21
west.manifest: running 'git fetch -f --tags --depth 1 -- https://github.com/acpica/acpica refs/tags/R01_05_21' in /home/jlvillal/testing/tools/acpica
remote: Enumerating objects: 36897, done.
remote: Counting objects: 100% (36897/36897), done.
remote: Compressing objects: 100% (14091/14091), done.
remote: Total 36897 (delta 28345), reused 29660 (delta 22193), pack-reused 0
Receiving objects: 100% (36897/36897), 86.45 MiB | 14.42 MiB/s, done.
Resolving deltas: 100% (28345/28345), done.
From https://github.com/acpica/acpica
 * tag                 R01_05_21  -> FETCH_HEAD
 * [new tag]           HEAD       -> HEAD
 * [new tag]           R01_05_18  -> R01_05_18
 * [new tag]           R01_05_21  -> R01_05_21
 * [new tag]           R01_08_16  -> R01_08_16
 * [new tag]           R01_08_19  -> R01_08_19
 * [new tag]           R01_10_20  -> R01_10_20
 * [new tag]           R01_11_12  -> R01_11_12
 * [new tag]           R01_14_14  -> R01_14_14
 * [new tag]           R01_17_13  -> R01_17_13
 * [new tag]           R01_19_17  -> R01_19_17
 * [new tag]           R02_04_15  -> R02_04_15
 * [new tag]           R02_09_18  -> R02_09_18
 * [new tag]           R02_12_16  -> R02_12_16
 * [new tag]           R02_14_13  -> R02_14_13
 * [new tag]           R02_14_14  -> R02_14_14
 * [new tag]           R02_14_20  -> R02_14_20
 * [new tag]           R02_15_12  -> R02_15_12
 * [new tag]           R02_15_19  -> R02_15_19
 * [new tag]           R02_24_17  -> R02_24_17
 * [new tag]           R03_03_17  -> R03_03_17
 * [new tag]           R03_13_18  -> R03_13_18
 * [new tag]           R03_18_16  -> R03_18_16
 * [new tag]           R03_20_12  -> R03_20_12
 * [new tag]           R03_25_14  -> R03_25_14
 * [new tag]           R03_26_20  -> R03_26_20
 * [new tag]           R03_28_13  -> R03_28_13
 * [new tag]           R03_29_19  -> R03_29_19
 * [new tag]           R03_31_21  -> R03_31_21
 * [new tag]           R04_05_19  -> R04_05_19
 * [new tag]           R04_08_15  -> R04_08_15
 * [new tag]           R04_18_13  -> R04_18_13
 * [new tag]           R04_20_12  -> R04_20_12
 * [new tag]           R04_22_16  -> R04_22_16
 * [new tag]           R04_24_14  -> R04_24_14
 * [new tag]           R04_27_18  -> R04_27_18
 * [new tag]           R04_30_20  -> R04_30_20
 * [new tag]           R05_08_18  -> R05_08_18
 * [new tag]           R05_09_19  -> R05_09_19
 * [new tag]           R05_15_15  -> R05_15_15
 * [new tag]           R05_17_13  -> R05_17_13
 * [new tag]           R05_18_12  -> R05_18_12
 * [new tag]           R05_27_16  -> R05_27_16
 * [new tag]           R05_28_20  -> R05_28_20
 * [new tag]           R05_31_17  -> R05_31_17
 * [new tag]           R05_31_18  -> R05_31_18
 * [new tag]           R061615    -> R061615
 * [new tag]           R06_04_21  -> R06_04_21
 * [new tag]           R06_19_15  -> R06_19_15
 * [new tag]           R06_20_12  -> R06_20_12
 * [new tag]           R06_26_13  -> R06_26_13
 * [new tag]           R06_27_14  -> R06_27_14
 * [new tag]           R06_29_17  -> R06_29_17
 * [new tag]           R06_29_18  -> R06_29_18
 * [new tag]           R07_03_19  -> R07_03_19
 * [new tag]           R07_11_12  -> R07_11_12
 * [new tag]           R07_17_15  -> R07_17_15
 * [new tag]           R07_17_20  -> R07_17_20
 * [new tag]           R07_24_14  -> R07_24_14
 * [new tag]           R07_25_13  -> R07_25_13
 * [new tag]           R07_28_17  -> R07_28_17
 * [new tag]           R07_29_16  -> R07_29_16
 * [new tag]           R07_30_21  -> R07_30_21
 * [new tag]           R08_10_18  -> R08_10_18
 * [new tag]           R08_16_12  -> R08_16_12
 * [new tag]           R08_16_19  -> R08_16_19
 * [new tag]           R08_18_15  -> R08_18_15
 * [new tag]           R08_23_13  -> R08_23_13
 * [new tag]           R08_28_14  -> R08_28_14
 * [new tag]           R08_31_16  -> R08_31_16
 * [new tag]           R08_31_17  -> R08_31_17
 * [new tag]           R09_13_12  -> R09_13_12
 * [new tag]           R09_22_11  -> R09_22_11
 * [new tag]           R09_25_20  -> R09_25_20
 * [new tag]           R09_26_14  -> R09_26_14
 * [new tag]           R09_27_13  -> R09_27_13
 * [new tag]           R09_27_18  -> R09_27_18
 * [new tag]           R09_29_17  -> R09_29_17
 * [new tag]           R09_30_15  -> R09_30_15
 * [new tag]           R09_30_16  -> R09_30_16
 * [new tag]           R09_30_21  -> R09_30_21
 * [new tag]           R10_03_18  -> R10_03_18
 * [new tag]           R10_18_12  -> R10_18_12
 * [new tag]           R10_18_19  -> R10_18_19
 * [new tag]           R10_31_18  -> R10_31_18
 * [new tag]           R11_07_14  -> R11_07_14
 * [new tag]           R11_10_17  -> R11_10_17
 * [new tag]           R11_13_20  -> R11_13_20
 * [new tag]           R11_14_12  -> R11_14_12
 * [new tag]           R11_15_13  -> R11_15_13
 * [new tag]           R11_17_16  -> R11_17_16
 * [new tag]           R11_23_11  -> R11_23_11
 * [new tag]           R11_24_15  -> R11_24_15
 * [new tag]           R12_13_18  -> R12_13_18
 * [new tag]           R12_13_19  -> R12_13_19
 * [new tag]           R12_14_17  -> R12_14_17
 * [new tag]           R12_15_17  -> R12_15_17
 * [new tag]           R12_17_20  -> R12_17_20
 * [new tag]           R12_18_13  -> R12_18_13
 * [new tag]           R12_18_15  -> R12_18_15
 * [new tag]           R12_20_12  -> R12_20_12
 * [new tag]           R12_22_16  -> R12_22_16
west.manifest: "git fetch -f --tags --depth 1 -- https://github.com/acpica/acpica refs/tags/R01_05_21" exit code: 0 stdout: None stderr: None
west.manifest: running 'git rev-parse 'FETCH_HEAD^{commit}^{commit}'' in /home/jlvillal/testing/tools/acpica
west.manifest: "git rev-parse 'FETCH_HEAD^{commit}^{commit}'" exit code: 0 stdout: b'28cb42013541950cf378582a5a5a5587061498ca\n' stderr: b''
west.manifest: running 'git update-ref -m 'west update: moving to 28cb42013541950cf378582a5a5a5587061498ca' refs/heads/manifest-rev 28cb42013541950cf378582a5a5a5587061498ca' in /home/jlvillal/testing/tools/acpica
west.manifest: "git update-ref -m 'west update: moving to 28cb42013541950cf378582a5a5a5587061498ca' refs/heads/manifest-rev 28cb42013541950cf378582a5a5a5587061498ca" exit code: 0 stdout: None stderr: None
west.manifest: running 'git for-each-ref '--format=%(refname)' -- 'refs/west/**'' in /home/jlvillal/testing/tools/acpica
west.manifest: "git for-each-ref '--format=%(refname)' -- 'refs/west/**'" exit code: 0 stdout: b'' stderr: None
west.manifest: running 'git show-ref --quiet --head /' in /home/jlvillal/testing/tools/acpica
west.manifest: "git show-ref --quiet --head /" exit code: 1 stdout: None stderr: None
west.manifest: running 'git checkout --detach refs/heads/manifest-rev' in /home/jlvillal/testing/tools/acpica
HEAD is now at 28cb4201 Update version to 20210105
west.manifest: "git checkout --detach refs/heads/manifest-rev" exit code: 0 stdout: None stderr: None
west.manifest: running 'git rev-parse 'refs/heads/manifest-rev^{commit}'' in /home/jlvillal/testing/tools/acpica
west.manifest: "git rev-parse 'refs/heads/manifest-rev^{commit}'" exit code: 0 stdout: b'28cb42013541950cf378582a5a5a5587061498ca\n' stderr: b''
west.manifest: running 'git rev-parse --abbrev-ref HEAD' in /home/jlvillal/testing/tools/acpica
warning: refname 'HEAD' is ambiguous.
error: refname 'HEAD' is ambiguous
west.manifest: "git rev-parse --abbrev-ref HEAD" exit code: 0 stdout: b'' stderr: None
west.manifest: running 'git merge-base --is-ancestor 28cb42013541950cf378582a5a5a5587061498ca' in /home/jlvillal/testing/tools/acpica
usage: git merge-base [-a | --all] <commit> <commit>...
   or: git merge-base [-a | --all] --octopus <commit>...
   or: git merge-base --independent <commit>...
   or: git merge-base --is-ancestor <commit> <commit>
   or: git merge-base --fork-point <ref> [<commit>]

    -a, --all             output all common ancestors
    --octopus             find ancestors for a single n-way merge
    --independent         list revs not reachable from others
    --is-ancestor         is the first one ancestor of the other?
    --fork-point          find where <commit> forked from reflog of <ref>

west.manifest: "git merge-base --is-ancestor 28cb42013541950cf378582a5a5a5587061498ca" exit code: 129 stdout: None stderr: None
Traceback (most recent call last):
  File "/home/jlvillal/.local/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 781, in main
    app.run(argv or sys.argv[1:])
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 336, in run_command
    cmd.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/commands.py", line 140, in run
    self.do_run(args, unknown)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 802, in do_run
    self.update_all()
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 869, in update_all
    self.update(project)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 1048, in update
    current_branch, is_ancestor, try_rebase = self.decide_update_strategy(
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 1355, in decide_update_strategy
    is_ancestor = project.is_ancestor_of(sha, current_branch)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/manifest.py", line 876, in is_ancestor_of
    raise RuntimeError(f'unexpected git merge-base result {rc}')
RuntimeError: unexpected git merge-base result 129


```

**Comment by JohnVillalovos** [comment]
As a note I have also tried the `west.yml` file without the `clone-depth: 1` value and same issue.

**Comment by marc-hb** [comment]
Can you please try this?
```diff
-      revision: refs/tags/R01_05_21
+      revision: R01_05_21
```

Thanks for the verbose trace, this can be very useful but what is the terser error message first?

PS: "crash" sounds a bit extreme and a bit "clickbaity" (which seems to have worked!)

**Comment by JohnVillalovos** [comment]
> Can you please try this?
> 
> ```diff
> -      revision: refs/tags/R01_05_21
> +      revision: R01_05_21
> ```

```
$ cat west.yml
manifest:
  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: acpica
      remote: github
      repo-path: acpica/acpica
      path: tools/acpica
      revision: R01_05_21
      # revision: refs/tags/R01_05_21
      clone-depth: 1
```

```
$ west update
=== updating acpica (tools/acpica):
--- acpica: initializing
Initialized empty Git repository in /home/jlvillal/testing/tools/acpica/.git/
--- acpica: fetching, need revision R01_05_21
remote: Enumerating objects: 36897, done.
remote: Counting objects: 100% (36897/36897), done.
remote: Compressing objects: 100% (14091/14091), done.
remote: Total 36897 (delta 28345), reused 29660 (delta 22193), pack-reused 0
Receiving objects: 100% (36897/36897), 86.45 MiB | 9.35 MiB/s, done.
Resolving deltas: 100% (28345/28345), done.
From https://github.com/acpica/acpica
 * tag                 R01_05_21  -> FETCH_HEAD
 * [new tag]           HEAD       -> HEAD
 * [new tag]           R01_05_18  -> R01_05_18
 * [new tag]           R01_05_21  -> R01_05_21
 * [new tag]           R01_08_16  -> R01_08_16
 * [new tag]           R01_08_19  -> R01_08_19
 * [new tag]           R01_10_20  -> R01_10_20
 * [new tag]           R01_11_12  -> R01_11_12
 * [new tag]           R01_14_14  -> R01_14_14
 * [new tag]           R01_17_13  -> R01_17_13
 * [new tag]           R01_19_17  -> R01_19_17
 * [new tag]           R02_04_15  -> R02_04_15
 * [new tag]           R02_09_18  -> R02_09_18
 * [new tag]           R02_12_16  -> R02_12_16
 * [new tag]           R02_14_13  -> R02_14_13
 * [new tag]           R02_14_14  -> R02_14_14
 * [new tag]           R02_14_20  -> R02_14_20
 * [new tag]           R02_15_12  -> R02_15_12
 * [new tag]           R02_15_19  -> R02_15_19
 * [new tag]           R02_24_17  -> R02_24_17
 * [new tag]           R03_03_17  -> R03_03_17
 * [new tag]           R03_13_18  -> R03_13_18
 * [new tag]           R03_18_16  -> R03_18_16
 * [new tag]           R03_20_12  -> R03_20_12
 * [new tag]           R03_25_14  -> R03_25_14
 * [new tag]           R03_26_20  -> R03_26_20
 * [new tag]           R03_28_13  -> R03_28_13
 * [new tag]           R03_29_19  -> R03_29_19
 * [new tag]           R03_31_21  -> R03_31_21
 * [new tag]           R04_05_19  -> R04_05_19
 * [new tag]           R04_08_15  -> R04_08_15
 * [new tag]           R04_18_13  -> R04_18_13
 * [new tag]           R04_20_12  -> R04_20_12
 * [new tag]           R04_22_16  -> R04_22_16
 * [new tag]           R04_24_14  -> R04_24_14
 * [new tag]           R04_27_18  -> R04_27_18
 * [new tag]           R04_30_20  -> R04_30_20
 * [new tag]           R05_08_18  -> R05_08_18
 * [new tag]           R05_09_19  -> R05_09_19
 * [new tag]           R05_15_15  -> R05_15_15
 * [new tag]           R05_17_13  -> R05_17_13
 * [new tag]           R05_18_12  -> R05_18_12
 * [new tag]           R05_27_16  -> R05_27_16
 * [new tag]           R05_28_20  -> R05_28_20
 * [new tag]           R05_31_17  -> R05_31_17
 * [new tag]           R05_31_18  -> R05_31_18
 * [new tag]           R061615    -> R061615
 * [new tag]           R06_04_21  -> R06_04_21
 * [new tag]           R06_19_15  -> R06_19_15
 * [new tag]           R06_20_12  -> R06_20_12
 * [new tag]           R06_26_13  -> R06_26_13
 * [new tag]           R06_27_14  -> R06_27_14
 * [new tag]           R06_29_17  -> R06_29_17
 * [new tag]           R06_29_18  -> R06_29_18
 * [new tag]           R07_03_19  -> R07_03_19
 * [new tag]           R07_11_12  -> R07_11_12
 * [new tag]           R07_17_15  -> R07_17_15
 * [new tag]           R07_17_20  -> R07_17_20
 * [new tag]           R07_24_14  -> R07_24_14
 * [new tag]           R07_25_13  -> R07_25_13
 * [new tag]           R07_28_17  -> R07_28_17
 * [new tag]           R07_29_16  -> R07_29_16
 * [new tag]           R07_30_21  -> R07_30_21
 * [new tag]           R08_10_18  -> R08_10_18
 * [new tag]           R08_16_12  -> R08_16_12
 * [new tag]           R08_16_19  -> R08_16_19
 * [new tag]           R08_18_15  -> R08_18_15
 * [new tag]           R08_23_13  -> R08_23_13
 * [new tag]           R08_28_14  -> R08_28_14
 * [new tag]           R08_31_16  -> R08_31_16
 * [new tag]           R08_31_17  -> R08_31_17
 * [new tag]           R09_13_12  -> R09_13_12
 * [new tag]           R09_22_11  -> R09_22_11
 * [new tag]           R09_25_20  -> R09_25_20
 * [new tag]           R09_26_14  -> R09_26_14
 * [new tag]           R09_27_13  -> R09_27_13
 * [new tag]           R09_27_18  -> R09_27_18
 * [new tag]           R09_29_17  -> R09_29_17
 * [new tag]           R09_30_15  -> R09_30_15
 * [new tag]           R09_30_16  -> R09_30_16
 * [new tag]           R09_30_21  -> R09_30_21
 * [new tag]           R10_03_18  -> R10_03_18
 * [new tag]           R10_18_12  -> R10_18_12
 * [new tag]           R10_18_19  -> R10_18_19
 * [new tag]           R10_31_18  -> R10_31_18
 * [new tag]           R11_07_14  -> R11_07_14
 * [new tag]           R11_10_17  -> R11_10_17
 * [new tag]           R11_13_20  -> R11_13_20
 * [new tag]           R11_14_12  -> R11_14_12
 * [new tag]           R11_15_13  -> R11_15_13
 * [new tag]           R11_17_16  -> R11_17_16
 * [new tag]           R11_23_11  -> R11_23_11
 * [new tag]           R11_24_15  -> R11_24_15
 * [new tag]           R12_13_18  -> R12_13_18
 * [new tag]           R12_13_19  -> R12_13_19
 * [new tag]           R12_14_17  -> R12_14_17
 * [new tag]           R12_15_17  -> R12_15_17
 * [new tag]           R12_17_20  -> R12_17_20
 * [new tag]           R12_18_13  -> R12_18_13
 * [new tag]           R12_18_15  -> R12_18_15
 * [new tag]           R12_20_12  -> R12_20_12
 * [new tag]           R12_22_16  -> R12_22_16
HEAD is now at 28cb4201 Update version to 20210105
warning: refname 'HEAD' is ambiguous.
error: refname 'HEAD' is ambiguous
usage: git merge-base [-a | --all] <commit> <commit>...
   or: git merge-base [-a | --all] --octopus <commit>...
   or: git merge-base --independent <commit>...
   or: git merge-base --is-ancestor <commit> <commit>
   or: git merge-base --fork-point <ref> [<commit>]

    -a, --all             output all common ancestors
    --octopus             find ancestors for a single n-way merge
    --independent         list revs not reachable from others
    --is-ancestor         is the first one ancestor of the other?
    --fork-point          find where <commit> forked from reflog of <ref>

Traceback (most recent call last):
  File "/home/jlvillal/.local/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 781, in main
    app.run(argv or sys.argv[1:])
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/main.py", line 336, in run_command
    cmd.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/commands.py", line 140, in run
    self.do_run(args, unknown)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 802, in do_run
    self.update_all()
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 869, in update_all
    self.update(project)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 1048, in update
    current_branch, is_ancestor, try_rebase = self.decide_update_strategy(
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/app/project.py", line 1355, in decide_update_strategy
    is_ancestor = project.is_ancestor_of(sha, current_branch)
  File "/home/jlvillal/.local/lib/python3.10/site-packages/west/manifest.py", line 876, in is_ancestor_of
    raise RuntimeError(f'unexpected git merge-base result {rc}')
RuntimeError: unexpected git merge-base result 129
```

> Thanks for the verbose trace, this can be very useful but what is the terser error message first?

Ran it this time without verbose

**Comment by JohnVillalovos** [comment]
Think the issue maybe this: https://github.com/acpica/acpica/issues/739

**Comment by marc-hb** [comment]
That acpica git repo is broken. @acpibob created a tag named `HEAD` 4 days ago: https://github.com/acpica/acpica/releases/tag/HEAD

```
git clone https://github.com/acpica/acpica/
git rev-parse HEAD
warning: refname 'HEAD' is ambiguous.
5c20304bc45b7954e1a4f7e536c167b901838cfb
```

**Comment by JohnVillalovos** [comment]
I'm going to close this. Feel free to re-open if someone thinks west should work around repositories that use `HEAD` as a tag name.

**Comment by acpibob** [comment]
Well, I can delete the tag if someone can tell me how to do it.
Thx,
Bob

**Comment by marc-hb** [comment]
Thanks! Looks like it's gone now: https://github.com/acpica/acpica/releases/tag/HEAD => not found.

Make sure it's also removed from any local clone you have. Because tags are supposed to be immutable; they propagate very (too?) quickly and easily; think Hydra heads...
