### ISSUE TITLE
Exporting SBOM fails

### ISSUE THREAD

**Issue by traluke** [zephyrproject-rtos/west#707]
I tried to export the SBOM according to the [documentation](https://docs.zephyrproject.org/latest/develop/west/zephyr-cmds.html#software-bill-of-materials-west-spdx), however, the last command fails with below error:

```
vscode:~$ west spdx -d FOO
parsing CMake Cache file
parsing CMake Codemodel files
setting up SPDX documents
walking through targets
Traceback (most recent call last):
  File "/home/vscode/.local/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.10/site-packages/west/app/main.py", line 1085, in main
    app.run(argv or sys.argv[1:])
  File "/home/vscode/.local/lib/python3.10/site-packages/west/app/main.py", line 244, in run
    self.run_command(argv, early_args)
  File "/home/vscode/.local/lib/python3.10/site-packages/west/app/main.py", line 505, in run_command
    self.run_extension(args.command, argv)
  File "/home/vscode/.local/lib/python3.10/site-packages/west/app/main.py", line 654, in run_extension
    self.cmd.run(args, unknown, self.topdir, manifest=self.manifest,
  File "/home/vscode/.local/lib/python3.10/site-packages/west/commands.py", line 194, in run
    self.do_run(args, unknown)
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/spdx.py", line 65, in do_run
    do_run_spdx(args)
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/spdx.py", line 114, in do_run_spdx
    makeSPDX(cfg)
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/zspdx/sbom.py", line 81, in makeSPDX
    retval = w.makeDocuments()
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/zspdx/walker.py", line 92, in makeDocuments
    self.walkTargets()
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/zspdx/walker.py", line 276, in walkTargets
    self.collectTargetDependencies(cfgTargets, cfgTarget, pkg)
  File "/home/vscode/workspaces/external_dependencies/zephyr/scripts/west_commands/zspdx/walker.py", line 471, in collectTargetDependencies
    rd.ownerFileAbspath = pkg.targetBuildFile.abspath
AttributeError: 'NoneType' object has no attribute 'abspath'
```

Found also that somebody else was struggling with it online: https://devzone.nordicsemi.com/f/nordic-q-a/91659/how-to-generate-sbom

Any suggestions?

**Comment by marc-hb** [comment]
As you can see from the logs, `zephyr/scripts/west_commands/zspdx/walker.py` is not part of `west`, it's part of Zephyr. So I'm transferring this bug.

Can you please run `west -v -v -v -v spdx -d FOO`, redirect the logs and search for any such message in them: `but file not found after build`

See commit c2ae5b3bbf1af5 why.
