### ISSUE TITLE
Log message in west command __init__ func may cause infinite call stack

### ISSUE THREAD

**Issue by yvesll** [zephyrproject-rtos/west#708]
If use any log api like `self.err` or `self.die` in WestCommand's `__init__` function, it may throw following exception:
```python
  ........................

  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 287, in _get_config
    self.die(f"can't run west {self.name}; it requires config "
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 504, in die
    self.err(*args, fatal=True)
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 487, in err
    if self.color_ui:
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 510, in color_ui
    return self.config.getboolean('color.ui', default=True)
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 287, in _get_config
    self.die(f"can't run west {self.name}; it requires config "
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 504, in die
    self.err(*args, fatal=True)
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 487, in err
    if self.color_ui:
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 510, in color_ui
    return self.config.getboolean('color.ui', default=True)
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 287, in _get_config
    self.die(f"can't run west {self.name}; it requires config "
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 504, in die
    self.err(*args, fatal=True)
  File "/home/yves/.local/lib/python3.10/site-packages/west/commands.py", line 487, in err
    if self.color_ui:
RecursionError: maximum recursion depth exceeded
```

In `__init__` phase, the variable `config` is None, but the property `color_ui` try infinitely get it from `config`

**Comment by marc-hb** [comment]
Thanks for the report! Can you please share:
- The west commit used
- The one-line diff
- Just in case, the manifest used.

**Comment by yvesll** [comment]
Hi, @marc-hb , sorry my description is not quite clear. The issue happens on a west extension command and my installed west version is **v1.2.0**

Hook following extension command to a west project can reproduce the issue.
```python
# example.py
from west.commands import WestCommand
class Example(WestCommand):
    def __init__(self):
        super().__init__(
          'example',
          # Keep this in sync with the string in west-commands.yml.
          'example',
          "example")
        
        # This may raise an exception
        self.err("show a log")

    def do_add_parser(self, parser_adder):
        parser = self._parser(parser_adder, epilog='')
        return parser
    
    def do_run(self, args):
        pass
```

**Comment by marc-hb** [comment]
Initialization is often tricky: ordering dependencies can be hard. So it's not a major surprise that some things don't work (yet) in an `__init__()` method. I just had a look at initializations in zephyr/scripts/west_commands/ and none of them has any logic, just constants. This should probably be better documented but "In Rome, do as the Romans do?". I recommend you defer any logic somewhere after `__init__()` time.

This being said, error-handling should be better: better message and nothing should ever trigger an infinite loop/recursion.

**Comment by marc-hb** [comment]
@yvesll can you please explain what prompted you to close this?

**Comment by yvesll** [comment]
I think we should not put too complex logic in `__init__` func, as you say, its tricky.

**Comment by marc-hb** [comment]
Interesting...

https://github.com/zephyrproject-rtos/zephyr/actions/runs/27026151279/job/79766586099

```
/usr/bin/git log -1 --format=%H
f16a199b3f19d12bed2e55ab5fbd04e3f735bc26

  pip install -r scripts/requirements-actions.txt --require-hashes


Collecting west==1.5.0 (from -r scripts/requirements-actions.txt (line 1603))
  Using cached west-1.5.0-py3-none-any.whl (106 kB)




=================================== FAILURES ===================================
______________________ test_test_item_updates_source_dir _______________________

tmp_path = PosixPath('/tmp/pytest-of-runner/pytest-0/test_test_item_updates_source_0')
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fad9f8322b0>

    def test_test_item_updates_source_dir(tmp_path, monkeypatch):
        """Test: _resolve_test_item sets source_dir from test path, not CWD."""






        b.run_cmake = True
        b.build_dir = str(tmp_path / 'build')
    
>       b._run_cmake(board='native_sim', origin=None)

tests/test_build.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
build.py:694: in _run_cmake
    user_args = self.config.get('build.cmake-args', default=None)
                ^^^^^^^^^^^
/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/site-packages/west/commands.py:293: in _get_config
    self.die(f"can't run west {self.name}; it requires config "
/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/site-packages/west/commands.py:519: in die
    self.err(*args, fatal=True)
/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/site-packages/west/commands.py:502: in err
    if self.color_ui:
       ^^^^^^^^^^^^^
/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/site-packages/west/commands.py:529: in color_ui
    return self.config.getboolean('color.ui', default=True)
           ^^^^^^^^^^^
/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/site-packages/west/commands.py:293: in _get_config
    self.die(f"can't run west {self.name}; it requires config "
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
=========================== short test summary info ============================
FAILED tests/test_build.py::test_test_item_updates_source_dir - RecursionError: maximum recursion depth exceeded
======================== 1 failed, 896 passed in 4.15s =========================
Traceback (most recent call last):
  File "/home/runner/work/zephyr/zephyr/./scripts/west_commands/run_tests.py", line 37, in <module>
    subprocess.run(command, check=True, cwd=here)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.13/x64/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.13.13/x64/bin/python3', '-m', 'pytest']' returned non-zero exit status 1.
```
